name: Sync Dev with Main

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync Dev Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          git fetch origin
          
          git checkout dev
          git reset --hard origin/main
          
          git push origin dev --force-with-lease
